### PR TITLE
Few improvements

### PR DESCRIPTION
**Pull request by Git-North**
I have made a few improvements to the script such as Command Line Argument support and using aikars flags. The server also starts in 25 seconds if no input is entered after "L"

There are also a few "tweaks" such as using. amazon coretto and the removal of force online which was needed for velocity support but I understand those were put in for reasons.

Feel free to use my edits on your code (preferrably with merging the pr so I become an contributor.)

Thank you for making and showing this script to me.

### CODE REVIEW

**Comment by Git-North** [comment]
also a thing I wanted to do but couldnt figure out was to upnp'ing UDP port for mod support (Geyser, Voice Chat, Racknetify, and more)

**Comment by nanonestor** [comment]
Ok - a few things, none of this is meant to be taken as a snippy response - many of these things have been asked about for this script before and there are reasons (I feel) why they are how they are

- Some users are slow readers, would like time to read the information on the 'ready to launch' screen, or just want to wait for whatever reason - why there is no time limit on that screen
- Aikars flags are mostly bunk - several high level devs in the modding community argue that they do not help over for example cpw's args.  Also all of the popular sets of args that people have thrown around over the years are not really helpful whatsoever when using java 17 or 21 which modern versions are based on.  Yes the script does have some that they apply, they seem 'fine' and no different than any of the others realistically with performance.  And you *can* edit the startup args - you simply edit the universalator-settings.txt file.  All of this is usually well beyond the skillset of the average user of the script - advanced users doing these tweaks are the minority.
- I'd like to keep with using Adoptium.  It's a universally popular product published by the non profit organization Eclipse Foundation - as opposed to the very-for-profit Amazon.  Coretto is used for some flavors of java 8 in the linux version of the script because some arch types do not have an option at Adoptium.
- Most of the modding community shuns software piracy and the use of that in conjunction with offline-mode servers so that is why online-mode=true is enforced

Adding the option for UDP port forwarding in the UPNP could certainly done easily.  Pity that it always seems like that module only seems to work for users who don't need it, lol.

Mainly if users have a lot of issues using this for their particular needs they often are capable of just setting up modloader files manually honestly.  Note that in the case of needing Coretto for 'velocity support' one can have it installed as the OS java path, and using the OVERRIDE command to use that rather than the auto-Adoptium.

**Comment by nanonestor** [comment]
Using CURL by the way seems to be very flakey.  The powershell webclient downloading seems to be much more robust to succeed for some reason.  Maybe because it's a fairly new addition to windows, idk precisely.

**Comment by Git-North** [comment]
Yeah I completely understand, I honestly love this script and edited it to be more in line with my needs, I am a more advanced user compared to most people, I like to automate things that's why I added the feature where when you start the cmd using the `START "" "universalator" L` (or any other argument it can take) it acts like I entered that command and goes to that page, I added the timer only for the screen where it shows the IP thing before it start for this reason too

The reason for Amazon Coretto was I also like to _optimize_ things, I am very well aware they are not as FOSS as Adoptium, but I put functionality over FOSS, don't get me wrong I like FOSS but I need the mod compatibility.

The aikars flags was because I don't know any better, It seemed like a no brainer, if I can squeeze performance without modifying anything and do it across my server network, I'll take it

I like the online-mode, adds security and unifies the uuid's that's why I have it on on my velocity proxy. just needed to turn it off here so it would work. thought I'd remove the flying enforcement too while I am at it.

cURL is simply because I am more familiar with it.

**Comment by Git-North** [comment]
I just had done these changes already and thought I could maybe contribute in some way since I already had done these edits.

**Comment by nanonestor** [comment]
Yes thanks - obviously you are welcome to make your own fork how you'd like :D Including make the online mode situation not be automatically applied

The whole allow-flying=true is becasue a large number of mods add things that will count as flight auto-kicking players off of servers with the vanilla game mechanic thinking they're 'cheating'.  It's a pretty standard thing to always have on imho.

**Pull request closed without merging**
